[package]
name = "prai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.0", features = ["derive", "env"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
