default = "ollama"

[[profile]]
name = "ollama"
provider = "ollama"
url = "http://localhost:11434"
model = "codegemma:7b"

[[profile]]
name = "claude"
provider = "anthropic"
version = "2023-06-01"
model = "claude-3-sonnet-20240229"
# Add your api key
api_key = "<ANTHROPIC_API_KEY>"
max_tokens = 500
temperature = 0.3
top_p = 0.9

[[profile]]
name = "openai"
provider = "openai"
model = "gpt-4"
# Add your api key
api_key = "<OPENAI_API_KEY>"
base_url = "https://api.openai.com/v1"
max_tokens = 500
temperature = 0.3
top_p = 0.9
frequency_penalty = 0.0
presence_penalty = 0.0

[[profile]]
name = "gemini"
provider = "google"
model = "gemini-pro"
# Add your api key
api_key = "<GOOGLE_API_KEY>"
base_url = "https://generativelanguage.googleapis.com/v1beta"
max_tokens = 500
temperature = 0.3
top_p = 0.9
